name: Coderco secrets ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkoout code
      uses: actions/checkout@v2


    - name: use secret
      run: echo the secret is ${{ secrets.MY_SECRET }}


    - name: use secret as env var
      run: echo "the secret is $MY_SECRET"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}